"""Train local sklearn detectors from CSV files.

Demo datasets generated by scripts/generate_sample_data.py are synthetic and
must not be presented as real research corpora.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from src.config import PROJECT_ROOT
from src.network_detector import NETWORK_FEATURE_ORDER, flow_vector
from src.schemas import NetworkFlowRequest
from src.security import parse_url_safely, sha256_file
from src.url_detector import URL_FEATURE_ORDER, url_features

SEED = 42


def _require_columns(df: pd.DataFrame, columns: list[str], name: str) -> None:
    missing = [c for c in columns if c not in df.columns]
    if missing:
        raise SystemExit(f"{name} is missing required columns: {missing}. Found: {list(df.columns)}")


def _warn_imbalance(y: pd.Series, name: str) -> None:
    counts = y.value_counts(normalize=True)
    print(f"{name} class distribution:\n{counts.to_string()}")
    if counts.min() < 0.2:
        print(f"WARNING: {name} is class-imbalanced. Metrics may overstate majority-class accuracy.")


def train_sms(df: pd.DataFrame) -> tuple[Pipeline, dict]:
    _require_columns(df, ["text", "label"], "sms_spam.csv")
    _warn_imbalance(df["label"], "sms")
    x_train, x_test, y_train, y_test = train_test_split(
        df["text"].astype(str), df["label"].astype(str), test_size=0.25, random_state=SEED, stratify=df["label"]
    )
    model = Pipeline(
        [
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=4000)),
            ("clf", LogisticRegression(max_iter=400, class_weight="balanced", random_state=SEED)),
        ]
    )
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    print("SMS classification report:\n", classification_report(y_test, pred, zero_division=0))
    print("SMS confusion matrix:\n", confusion_matrix(y_test, pred))
    f1 = float(f1_score(y_test, pred, average="macro", zero_division=0))
    return model, {
        "f1_macro": f1,
        "labels": sorted(df["label"].astype(str).unique().tolist()),
        "feature_schema": ["text"],
    }


def _url_row(url: str) -> list[float] | None:
    try:
        parsed = parse_url_safely(url, max_length=4096, allow_private=True)
    except Exception:
        return None
    feats = url_features(url, parsed, None)
    return [feats[k] for k in URL_FEATURE_ORDER]


def train_url(df: pd.DataFrame) -> tuple[RandomForestClassifier, dict]:
    _require_columns(df, ["url", "label"], "url_dataset.csv")
    rows = []
    labels = []
    skipped = 0
    for url, label in zip(df["url"].astype(str), df["label"].astype(str)):
        vec = _url_row(url)
        if vec is None:
            skipped += 1
            continue
        rows.append(vec)
        labels.append(label)
    if skipped:
        print(f"WARNING: skipped {skipped} URLs that failed safe parsing (possible leakage if labels depend on fetch).")
    if len(rows) < 8:
        raise SystemExit("Not enough parseable URLs to train.")
    y = pd.Series(labels)
    _warn_imbalance(y, "url")
    x_train, x_test, y_train, y_test = train_test_split(rows, labels, test_size=0.25, random_state=SEED, stratify=labels)
    model = RandomForestClassifier(n_estimators=80, random_state=SEED, class_weight="balanced")
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    print("URL classification report:\n", classification_report(y_test, pred, zero_division=0))
    print("URL confusion matrix:\n", confusion_matrix(y_test, pred))
    return model, {
        "f1_macro": float(f1_score(y_test, pred, average="macro", zero_division=0)),
        "labels": sorted(set(labels)),
        "feature_schema": URL_FEATURE_ORDER,
    }


def train_network(df: pd.DataFrame) -> tuple[RandomForestClassifier, dict]:
    needed = [
        "duration",
        "protocol",
        "src_port",
        "dst_port",
        "fwd_packets",
        "bwd_packets",
        "bytes_transferred",
        "packet_rate",
        "failed_count",
        "repeated_dst",
        "conn_freq",
        "label",
    ]
    _require_columns(df, needed, "network_flows.csv")
    rows = []
    labels = []
    for rec in df.to_dict(orient="records"):
        flow = NetworkFlowRequest(
            duration=rec.get("duration", 0),
            protocol=str(rec.get("protocol", "tcp")),
            src_port=int(rec.get("src_port", 0)),
            dst_port=int(rec.get("dst_port", 0)),
            fwd_packets=int(rec.get("fwd_packets", 0)),
            bwd_packets=int(rec.get("bwd_packets", 0)),
            bytes_transferred=int(rec.get("bytes_transferred", 0)),
            packet_rate=float(rec.get("packet_rate", 0)),
            failed_count=int(rec.get("failed_count", 0)),
            repeated_dst=int(rec.get("repeated_dst", 0)),
            conn_freq=float(rec.get("conn_freq", 0)),
            syn_count=int(rec.get("syn_count", 0) or 0),
            rst_count=int(rec.get("rst_count", 0) or 0),
        )
        rows.append(flow_vector(flow))
        labels.append(str(rec["label"]))
    _warn_imbalance(pd.Series(labels), "network")
    x_train, x_test, y_train, y_test = train_test_split(rows, labels, test_size=0.25, random_state=SEED, stratify=labels)
    model = RandomForestClassifier(n_estimators=80, random_state=SEED, class_weight="balanced")
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    print("Network classification report:\n", classification_report(y_test, pred, zero_division=0))
    print("Network confusion matrix:\n", confusion_matrix(y_test, pred))
    return model, {
        "f1_macro": float(f1_score(y_test, pred, average="macro", zero_division=0)),
        "labels": sorted(set(labels)),
        "feature_schema": NETWORK_FEATURE_ORDER,
    }


def _write_model(path: Path, model: object, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise SystemExit(f"Refusing to overwrite {path}. Pass --allow-overwrite or choose another --model-dir.")
    joblib.dump(model, path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default=str(PROJECT_ROOT / "data"))
    parser.add_argument("--model-dir", default=str(PROJECT_ROOT / "models"))
    parser.add_argument("--allow-overwrite", action="store_true")
    args = parser.parse_args()
    data_dir = Path(args.data_dir)
    model_dir = Path(args.model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)

    sms_path = data_dir / "sms_spam.csv"
    url_path = data_dir / "url_dataset.csv"
    net_path = data_dir / "network_flows.csv"
    if not sms_path.is_file() or not url_path.is_file() or not net_path.is_file():
        raise SystemExit("Dataset CSVs missing. Run: python scripts/generate_sample_data.py")

    import sklearn

    metadata: dict = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sklearn_version": sklearn.__version__,
        "joblib_version": joblib.__version__,
        "random_seed": SEED,
        "note": "If trained on generate_sample_data.py output, artifacts are DEMO models only.",
    }

    sms_model, sms_meta = train_sms(pd.read_csv(sms_path))
    sms_file = model_dir / "sms_model.joblib"
    _write_model(sms_file, sms_model, args.allow_overwrite)
    metadata["sms"] = {
        **sms_meta,
        "status": "trained",
        "demo": True,
        "model_version": "sms-demo-1.0",
        "dataset_name": sms_path.name,
        "sha256": sha256_file(sms_file),
    }

    url_model, url_meta = train_url(pd.read_csv(url_path))
    url_file = model_dir / "url_model.joblib"
    _write_model(url_file, url_model, args.allow_overwrite)
    metadata["url"] = {
        **url_meta,
        "status": "trained",
        "demo": True,
        "model_version": "url-demo-1.0",
        "dataset_name": url_path.name,
        "sha256": sha256_file(url_file),
    }

    net_model, net_meta = train_network(pd.read_csv(net_path))
    net_file = model_dir / "network_model.joblib"
    _write_model(net_file, net_model, args.allow_overwrite)
    metadata["network"] = {
        **net_meta,
        "status": "trained",
        "demo": True,
        "model_version": "network-demo-1.0",
        "dataset_name": net_path.name,
        "sha256": sha256_file(net_file),
    }

    (model_dir / "model_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Wrote models and metadata to {model_dir}")


if __name__ == "__main__":
    main()
